---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demoapp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: demoapp
      sourceRef:
        kind: GitRepository
        name: demoapp
  install: {}
  interval: 30s
  targetNamespace: production
