---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-production
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  install: {}
  interval: 30s
  targetNamespace: production
  values:
    image:
      tag: 2.9.9
    ingress:
      host: aks-samik-dns-9ba89391.hcp.westeurope.azmk8s.io
