apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.name}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{.Values.container.port}}
